const router = require("express").Router()
const itemsRouter = require("./api/ItemsRouter")
const restaurantsRouter = require("./api/RestaurantsRouter")
const superCategoriesRouter = require("./api/SuperCategoriesRouter")
const usersRouter = require("./api/UsersRouter")
const favouritesRouter = require("./api/FavouritesRouter")
const cartsRouter = require("./api/CartsRouter")
const couponCodesRouter = require("./api/CouponCodesRouter")
const ordersRouter = require("./api/OrdersRouter")
const addressRouter = require("./api/AddressRouter")
const authRouter = require("./api/AuthRouter")
const agentsRouter = require("./api/AgentsRouter")
const adminsRouter = require("./api/AdminsRouter")
const slidersRouter = require("./api/SlidersRouter")
const notificationsRouter = require("./api/NotificationsRouter")
const itemCategoriesRouter = require("./api/ItemCategoriesRouter")
const systemRouter = require("./api/SystemRouter")

router.use('/admins', adminsRouter)
router.use('/item_categories', itemCategoriesRouter)
router.use('/notifications', notificationsRouter)
router.use('/sliders', slidersRouter)
router.use('/agents', agentsRouter)
router.use('/address', addressRouter)
router.use('/auth', authRouter)
router.use('/orders', ordersRouter)
router.use('/carts', cartsRouter)
router.use('/coupon_codes', couponCodesRouter)
router.use('/favourites', favouritesRouter)
router.use('/items', itemsRouter)
router.use('/restaurants', restaurantsRouter)
router.use('/super_categories', superCategoriesRouter)
router.use('/users', usersRouter)
router.use('/system', systemRouter)

module.exports = router